### ISSUE TITLE
Client excepts on sending nothing

### ISSUE THREAD

**Issue by TKGP** [TKGP/Chernobyl-Relay-Chat#4]

**Comment by SanCampos** [comment]
Possible fix? 

~~https://github.com/TKGP/Chernobyl-Relay-Chat/pull/8/commits/de6ce8ab13ee64c69ff741af7b8ff4b339181314~~

~~https://github.com/TKGP/Chernobyl-Relay-Chat/pull/9~~

https://github.com/TKGP/Chernobyl-Relay-Chat/pull/10
